const IMAGES = {
    LOAD: 'IMAGES_LOAD',
    LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    LOAD_FAIL: 'IMAGES_LOAD_FAIL',
};

const IS_LOADING = "IS_LOADING";

const STATS = {
    LOAD: 'STATS_LOAD',
    LOAD_SUCCESS: 'STATS_LOAD_SUCCESS',
    LOAD_FAIL: 'STATS_LOAD_FAIL',
};

const LOGIN = {
    LOGIN_USER: "LOGIN_USER",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    CLEAR_AUTH_DATA: "CLEAR_AUTH_DATA"
};

export { IMAGES, STATS, IS_LOADING, LOGIN };
